# Chip 8

module Gosu
  class Window
  end
end

module Chip8
  module Components
    class Display

      WIDTH: Integer
      HEIGHT: Integer
      SCALE: Integer
      WHITE: Integer
      BLACK: Integer

      @cpu_status: CPUStatus
      @keyboard: Keyboard
      @clock: Clock
      @pixel_texture: Gosu::Image

      attr_reader display_buffer: untyped # TODO: Fix Matrix type later
      def initialize: (cpu_status: CPUStatus, keyboard: Keyboard, clock: Clock) -> void

      def create_pixel_texture: -> Gosu::Image

      def update: -> void
      def draw: -> void
      def update_display_buffer: (untyped new_display_matrix) -> void# TODO: Fix Matrix type later
      def clean_display: -> untyped # TODO: Fix Matrix type later
      def button_down: (Integer id) -> void
      def button_up: (Integer id) -> void
    end
  end
end
